# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --no-restore --configuration Release
  displayName: 'dotnet build'

- script: dotnet test --no-restore --configuration Release
  displayName: 'dotnet test'

- script: dotnet pack ./Dotnet.CodeGen/Dotnet.CodeGen.csproj --no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack'

# - task: NuGetCommand@2
#   inputs:
#     command: push
#     nuGetFeedType: external
#     publishFeedCredentials: 'nuget'
