# https://aka.ms/yaml

trigger:
- master

# pr:
#   autoCancel: true
#   branches:
#     include: master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build --no-restore --configuration Release
  displayName: 'dotnet build'

# - script: PATH="$PATH:$HOME/.dotnet/tools"
#   displayName: 'Adding dotnet global tools to PATH'

- script: dotnet test --no-restore --configuration Release
  displayName: 'dotnet test'

- script: dotnet test --no-restore --logger "trx;LogFileName=$(Build.ArtifactStagingDirectory)/testsResults.trx"
  displayName: 'dotnet test DEBUG (because not all are compiled in release)'

- task: PublishTestResults@2  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml
  condition: always()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '$(Build.ArtifactStagingDirectory)/testsResults.trx'

# - script: dotnet pack ./src/DocumentRefLoader/DocumentRefLoader.csproj --no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)
#   displayName: 'dotnet pack'
- script: dotnet pack ./src/Dotnet.CodeGenEngine/Dotnet.CodeGenEngine.csproj --no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack'
# - script: dotnet pack ./src/Dotnet.CodeGen/Dotnet.CodeGen.csproj --no-restore --configuration Release --output $(Build.ArtifactStagingDirectory)
#   displayName: 'dotnet pack'

- task: NuGetToolInstaller@1
  inputs:
    checkLatest: true 
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'BeeUP - Nuget - Public - OpenSource'

